### ISSUE TITLE
"issueベースの開発"レビュー依頼

### ISSUE THREAD

**Issue by Plum0329** [Plum0329/graduation_project#5]
### ■Webアプリの概要
このアプリは、日本の伝統的な短詩形である俳句と川柳に特化した、ユニークな投稿プラットフォームです。ユーザーは1日1回だけ、17音の句を画像と共に投稿できます。投稿された句に対して他のユーザーが句で感想を返すことができ、これは1日の投稿制限には含まれません。また、他のユーザーが投稿した画像に対して新たな句を詠むこともでき、同じ画像から生まれる様々な視点や解釈を共有することができます。タグ機能により俳句と川柳を分類し、いいね機能で人気の句を見つけることができます。

### ■1週間辺りの開発に向けられる時間
- 1週間あたり：20時間
（1日3時間程度を想定、ストーリーポイント1 = 2時間で換算）

### ■ProjectsのURL
https://github.com/users/Plum0329/projects/2/views/1

### ■MVPリリースまで
第1週 (11/13-11/19)
- [ ] 初期設定・環境構築 (3)
- [ ] デプロイ設定 (2)
- [ ] トップページの作成 (2)

第2週 (11/20-11/26)
- [ ] ユーザー登録機能 (3)
- [ ] ログイン機能 (2)
- [ ] 句の投稿機能 (3)

第3週 (11/27-12/3)
- [ ] 画像投稿機能 (4)
- [ ] タグ機能 (2)
- [ ] 1日1投稿制限機能 (2)

第4週 (12/4-12/10)
- [ ] いいね機能 (2)
- [ ] 句でのコメント機能 (3)
- [ ] 最終調整 (2)
- [ ] MVPレビュー依頼提出

### ■MVP後
- [ ] 通知機能（WebSocket）
- [ ] 画像サイズ統一（MiniMagick）
- [ ] 利用規約
- [ ] プライバシーポリシー
- [ ] お問い合わせ
- [ ] パスワードリセット機能
- [ ] RSpec（モデルテスト・システムテスト）
- [ ] レスポンシブ対応
- [ ] OGP設定

### ■MVPレビュー依頼予定日
予定日：2024年 12月 12日

**Comment by tmtkzk0823** [comment]
ご提出ありがとうございます。
以下、コメントになります。

---

- 「ログイン機能」のissueはありますが、「ログアウト機能」のissueが見当たらなかったのでご確認をお願いします。
- 句の投稿の機能はありますが、「編集」「削除」「一覧」などの機能を作成するissueが見当たらなかったのでこちらもご確認お願いします。

**Comment by Plum0329** [comment]
issueを修正しました。
句の編集はあえて実装しません。これは俳句・川柳の本質的な特徴である「一期一会」の精神を大切にするためです。

**Comment by kenchasonakai** [comment]
LGTMです！
