### ISSUE TITLE
MVPリリースレビュー依頼 12/5

### ISSUE THREAD

**Issue by Plum0329** [Plum0329/graduation_project#6]
12/5 MVPリリースレビュー依頼

**Comment by Tsuchiya2** [comment]
<img width="1243" alt="image" src="https://github.com/user-attachments/assets/27c40d72-56d3-426c-955e-4e344393dd64">

ご提出いただいたURLにアクセスしたところ、上記画面が出ましたが他ページへの動線もなく、サービスの確認ができませんでした。ご確認と対応をお願いいたします。

**Comment by kashiwagi-rena** [comment]
提出いただきありがとうございます。
以下、コメントです。

- バリデーションのメッセージを日本語訳していただきたいです。
- パスワードの設定の文字数などをユーザーに伝えてください。
<img width="905" alt="スクリーンショット 2024-11-22 20 08 16" src="https://github.com/user-attachments/assets/30b99654-d774-4720-8afb-f9e64fae6efd">

- 新規登録画面入力後にできれば、ホーム画面に飛んでいただくとユーザー視点で良いと思いました。
- 入力の制限に、「ひらがな・カタカナ」のみなのはなぜですか？（入力してみて疑問に思ったため聞いております！）

**Comment by Plum0329** [comment]
入力をひらがな・カタカナのみに限定している理由は、このアプリの核となる「17音」での投稿機能を優先したためです。単なる17文字の投稿では俳句・川柳の特徴が失われ、アプリの存在意義が薄れてしまいます。
また、将来的な音声読み上げ機能の実装も視野に入れています。
漢字入力等への対応については、以下の2つの方向性を検討中です：
1. 各種APIを活用した自動変換機能の実装
2. 17音入力後に漢字での清書を行う二段階投稿方式（17音をルビとして活用）

投稿文字数については、現在のテスト段階では0〜20文字に設定していますが、俳句の実際の音数（最大24音）に合わせた調整を検討中です。
MVPとしては、まず「17音の投稿」という基本機能の実装に注力しています。

**Comment by kashiwagi-rena** [comment]
ご返答いただきありがとうございます。

エラー画面の日本語化・新規登録後の自動ログイン確認いたしました！
また、入力をひらがな・カタカナのみに限定している理由について理解いたしました。

下記の実装の方をお願いいたします。

- パスワードの設定の文字数をユーザーに伝えてください。使える文字が限られている場合それも伝えてください。

**Comment by Plum0329** [comment]
パスワードの条件を明示しました。
[![Image from Gyazo](https://i.gyazo.com/1cdb0338275297420134f73b5a7d753d.png)](https://gyazo.com/1cdb0338275297420134f73b5a7d753d)
現時点では3文字以上という条件ですが、MVPリリース後パスワード強度を引き上げる予定です。

**Comment by Tsuchiya2** [comment]
機能確認が取れました。LGTMです。
引き続き本リリースに向けて開発頑張ってください。

以下、LGTMを出した方々に共通してお伝えしている内容になります。
（Webアプリを就職活動で活用される方向けの内容になります）

===== 本リリースまでに以下の項目を実装してください =====
□ 独自ドメイン反映
    -> DNSやSSLの対応も必要になるのでアピールになり、URLを書類等に記載するときの見栄えも良くなります。
□ OGP（静的 or 動的）
    -> SNS等でシェアするときの見栄えが良くなります。Webアプリであればどんなアプリでも取り入れられるので対応しておきましょう。
□ RSpec（モデルテスト+システムテスト or モデルテスト+リクエストテスト）
    -> 開発における品質の意識や開発効率の意識の高さをアピールできます。Request Specをメインに最低限各機能に正常にアクセスできるか程度はテストで確認できるようにしておきましょう。
□ CI（GitHubActions）
    -> 実際に開発現場でも使われており、アプリ外で技術のアピールが出来るものです。RSpecと合わせて実装を行いましょう。
□ Rubocopを使ってのリファクタリング
    -> Lintチェックツールは開発現場で広く使われています。コードのLintを整えておくことはチームで開発することを意識するうえでとても大切になるので取り入れておきましょう。

他のプログラミング学習者のWebアプリと異なることをアピールするために、よりインパクトのある機能を複数盛り込むことが重要になってきます。
□ SNSログイン（Google or LINE）
    -> ほとんどのアプリに取り入れられてユーザー体験の向上や技術のアピールにつながるので取り入れましょう。
□ 検索機能のアップデート（オートコンプリート、マルチ検索等）   ※検索機能がある場合
    -> 特にオートコンプリートは検索体験の向上だけではなくJS系の技術も取り入れていることをアピール出来るので積極的に取り入れましょう。

ユーザー体験という面では以下の項目も大切です。
□ オートログイン
    -> ユーザー登録後に再度ログイン操作を行わせないことでユーザー体験を向上させられます。
□ 使い方説明がある
    -> 初めて訪れたユーザーに呈して使い方の説明があることで体験を向上させられます。
□ レスポンシブ対応
    -> いずれのデバイスでも綺麗にサービスが活用できることで体験が良くなります。
□ 利用規約・プライバシーポリシーを未ログイン状態でも確認できる
    -> 利用規約・プライバシーポリシーがあることで、ちゃんとしたサービスという印象を与えられます。
□ ローディングアニメーション（処理が重い箇所）
    -> 処理が重い箇所に何の対応も無いとユーザーが正しく操作できたのか困惑してしまいます。そうした際はローディングアニメーションを表示させることで体験が向上します。
